# Generated by Django 2.2.1 on 2019-06-24 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PokeTraining', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='ev_trained',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='pkmn_type1',
            field=models.CharField(choices=[('NORMAL', 'Normal'), ('FIRE', 'Fire'), ('FIGHTING', 'Fighting'), ('WATER', 'Water'), ('FLYING', 'Flying'), ('GRASS', 'Grass'), ('POISON', 'Poison'), ('ELECTRIC', 'Electric'), ('GROUND', 'Ground'), ('PSYCHIC', 'Psychic'), ('ROCK', 'Rock'), ('ICE', 'Ice'), ('BUG', 'Bug'), ('DRAGON', 'Dragon'), ('GHOST', 'Ghost'), ('DARK', 'Dark'), ('STEEL', 'Steel'), ('FAIRY', 'Fairy')], default='NORMAL', max_length=40),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='pkmn_type2',
            field=models.CharField(choices=[('NORMAL', 'Normal'), ('FIRE', 'Fire'), ('FIGHTING', 'Fighting'), ('WATER', 'Water'), ('FLYING', 'Flying'), ('GRASS', 'Grass'), ('POISON', 'Poison'), ('ELECTRIC', 'Electric'), ('GROUND', 'Ground'), ('PSYCHIC', 'Psychic'), ('ROCK', 'Rock'), ('ICE', 'Ice'), ('BUG', 'Bug'), ('DRAGON', 'Dragon'), ('GHOST', 'Ghost'), ('DARK', 'Dark'), ('STEEL', 'Steel'), ('FAIRY', 'Fairy')], max_length=40, null=True),
        ),
    ]
