# Generated by Django 2.2.1 on 2019-07-06 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PokeTraining', '0003_pokemon_pkmn_gender'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attacks',
            options={'verbose_name': 'Attack', 'verbose_name_plural': 'Attacks'},
        ),
        migrations.AlterModelOptions(
            name='originaltrainer',
            options={'verbose_name': 'Original Trainer'},
        ),
        migrations.AlterModelOptions(
            name='pokemon',
            options={'ordering': ('pkmn_number',), 'verbose_name': 'Pokemon', 'verbose_name_plural': 'Pokemon'},
        ),
        migrations.AlterModelOptions(
            name='stats',
            options={'verbose_name': 'Stat', 'verbose_name_plural': 'Stats'},
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='held_item',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='pkmn_nickname',
            field=models.CharField(blank=True, max_length=40),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='pkmn_type2',
            field=models.CharField(blank=True, choices=[('NORMAL', 'Normal'), ('FIRE', 'Fire'), ('FIGHTING', 'Fighting'), ('WATER', 'Water'), ('FLYING', 'Flying'), ('GRASS', 'Grass'), ('POISON', 'Poison'), ('ELECTRIC', 'Electric'), ('GROUND', 'Ground'), ('PSYCHIC', 'Psychic'), ('ROCK', 'Rock'), ('ICE', 'Ice'), ('BUG', 'Bug'), ('DRAGON', 'Dragon'), ('GHOST', 'Ghost'), ('DARK', 'Dark'), ('STEEL', 'Steel'), ('FAIRY', 'Fairy')], max_length=40, null=True),
        ),
    ]
