# Generated by Django 4.2.4 on 2023-08-02 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PokeTraining', '0004_auto_20190706_0820'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='pkmn_language',
            field=models.CharField(choices=[('ENGLISH', 'English')], default='ENGLISH', max_length=40),
        ),
        migrations.AddField(
            model_name='pokemon',
            name='pkmn_markings',
            field=models.CharField(blank=True, choices=[('CIRCLE', 'Circle'), ('TRIANGLE', 'Triangle'), ('SQUARE', 'Square'), ('HEART', 'Heart'), ('STAR', 'Star'), ('DIAMOND', 'Diamond')], max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='ball_captured',
            field=models.CharField(choices=[('POKE', 'Pokeball'), ('GREAT', 'Great Ball'), ('ULTRA', 'Ultra Ball'), ('MASTER', 'Master Ball'), ('DIVE', 'Dive Ball'), ('FAST', 'Fast Ball'), ('BEAST', 'Beast Ball'), ('DUSK', 'Dusk Ball'), ('HEAL', 'Heal Ball'), ('LEVEL', 'Level Ball'), ('LOVE', 'Love Ball'), ('FRIEND', 'Friend Ball'), ('NEST', 'Nest Ball'), ('LUXURY', 'Luxury Ball'), ('HEAVY', 'Heavy Ball'), ('NET', 'Net Ball'), ('MOON', 'Moon Ball'), ('LURE', 'Lure Ball'), ('QUICK', 'Quick Ball'), ('PREMIER', 'Premier Ball'), ('TIMER', 'Timer Ball'), ('REPEAT', 'Repeat Ball'), ('SAFARI', 'Safari Ball'), ('SPORT', 'Sport Ball'), ('CHERISH', 'Cherish Ball'), ('DREAM', 'Dream Ball'), ('HISUI_POKE', 'Poke Ball (Hisuian)'), ('HISUI_GREAT', 'Great Ball (Hisuian)'), ('HISUI_ULTRA', 'Ultra Ball (Hisuian)'), ('HISUI_HEAVY', 'Heavy Ball (Hisuian)'), ('HISUI_LEADEN', 'Leaden Ball (Hisuian)'), ('HISUI_GIGATON', 'Gigaton Ball (Hisuian)'), ('HISUI_FEATHER', 'Feather Ball (Hisuian)'), ('HISUI_WING', 'Wing Ball (Hisuian)'), ('HISUI_JET', 'Jet Ball (Hisuian)'), ('HISUI_ORIGIN', 'Origin Ball (Hisuian)'), ('HISUI_STRANGE', 'Strange Ball (Hisuian)')], default='POKE', max_length=40),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='id',
            field=models.BigAutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='original_generation',
            field=models.CharField(choices=[('1', 'Kanto'), ('2', 'Johto'), ('3', 'Hoenn'), ('4', 'Sinnoh'), ('5', 'Unova'), ('6', 'Kalos'), ('7', 'Alola'), ('8', 'Galar'), ('9', 'Paldea')], default='7', max_length=40),
        ),
        migrations.AlterField(
            model_name='pokemon',
            name='pkmn_number',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
